### ISSUE TITLE
Does this package need the `gulp` dependency?

### ISSUE THREAD

**Issue by ChALkeR** [eduardolundgren/gulp-umd#19]
It doesn't seem to be `require`-d outside of tests.

Perhaps you should move it to [devDependencies](https://docs.npmjs.com/files/package.json#devdependencies) and/or [peerDependencies](https://docs.npmjs.com/files/package.json#peerdependencies).

**Comment by CodeMan99** [comment]
Same seems to be true of `nodeunit`. This package is huge and has lots of child dependencies.

**Comment by CodeMan99** [comment]
Created PR #20.

**Comment by eduardolundgren** [comment]
Merged. Thank you.

**Comment by CodeMan99** [comment]
@eduardolundgren Would you please publish a new version to npmjs? Needing to install the (now) devDependencies in production is eating up a heap of production server disk space. Sadly, this is a pretty large problem in my case.

**Comment by eduardolundgren** [comment]
done.
