### ISSUE TITLE
plugins must not require gulp as a dependency

### ISSUE THREAD

**Issue by stevelacy** [eduardolundgren/gulp-umd#9]
As per the guidelines: https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

**Comment by stringparser** [comment]
I think he didn't ment to, he only has it on [test](https://github.com/eduardolundgren/gulp-umd/blob/master/test/test.js#L3) so is just a devDependency in fact.

**Comment by CodeMan99** [comment]
Pretty sure this was solved by #20
